/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rec_Recorder */

#ifndef _Included_rec_Recorder
#define _Included_rec_Recorder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rec_Recorder
 * Method:    load
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rec_Recorder_load
  (JNIEnv *, jobject);

/*
 * Class:     rec_Recorder
 * Method:    get
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rec_Recorder_get
  (JNIEnv *, jobject);

/*
 * Class:     rec_Recorder
 * Method:    unload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rec_Recorder_unload
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
